#####################################################################
# Brain Tissue Module Mapping Pipeline
#####################################################################
# This script performs gene module mapping for downsream coeQTL analysis for brain tissue data.
# It processes each brain region and gene module to:
# 1. Calculate principal components of co-expressed genes
# 2. Map SNPs to genes within modules
# 3. Generate module-specific genotype data
# 4. Create mapping files for downstream QTL analysis
#
# Input Requirements:
# - Expression data (RData file with SummarizedExperiment object)
# - Gene module list (RDS file)
# - Genotype data (PLINK format)
#
# Output:
# - RData files for each module in networks containing:
#   * co-expressed genes
#   * Genotype data for module-specific SNPs
#   * SNP annotations
#####################################################################

## Required packages
if (!require("BiocManager")) install.packages("BiocManager")

# CRAN packages
if (!require("dplyr")) install.packages("dplyr")
if (!require("purrr")) install.packages("purrr") 
if (!require("parallel")) install.packages("parallel")
if (!require("limma")) install.packages("limma")

# Bioconductor packages
if (!require("SummarizedExperiment")) BiocManager::install("SummarizedExperiment")
if (!require("SNPRelate")) BiocManager::install("SNPRelate")

library(dplyr)
library(purrr)
library(parallel)
library(limma)
library(SummarizedExperiment)
library(SNPRelate)

## set working directory
# setwd("")


#################################################
## Helper Functions  ##
#################################################
source("./STEP3.Training_MODULE/mapping_helper_functions.r")


###################
## Configuration ##
###################

# Set paths
base_dir      = getwd()
#plink_version = paste0(base_dir,"/tools/plink2")
geno_dir      = paste0(base_dir, "/genotype/")
rnaseq_dir    = paste0(base_dir, "/rnaseq/")
data_dir      = paste0(base_dir, "/data/")

# Output directory
output_dir = paste0(base_dir, "/STEP3.Training_MODULE/output/")

# Input files
geno_file                  = paste0(geno_dir, "your_genotype_prefix")
networks_file              = paste0(data_dir, "coexpression_network.rds") ## your coexpression networks
snplist_file               = list.files(paste0(output_dir))[grepl("snpList",list.files(paste0(output_dir)))] ## Files generated by 1.prepare_mapping.R
expr_file                  = paste0(rnaseq_dir, "your_rnaseq.RData")


# Parameters
brain_regions = c('dlpfc') ## Specify all available regions 
n_cores       = 1                ## Specify more cores to run code in parallel on ubuntu terminal


#######
## Usage
#######
if(TRUE) {
    # configuration with all parameters defined
    config = list(
        expression_file    = expr_file,
        networks_list_file = networks_file,
        genotype_path      = geno_file,
        output_dir         = output_dir,
        brain_regions      = brain_regions,
        snplist_file       = file.path(output_dir,snplist_file),  
        excluded_networks  = c("Fromer2016_case|Pergola2017|hippo.noQSVAremoved|dentate.QSVAremoved"), ## network name to exlude
        excluded_modules   = "grey",  # Exclude the "grey" module containing not correlated genes
        mc_cores           = n_cores
    )
    
    # Run pipeline
    run_mapping_pipeline(config)
} 
